name: pos_tipo_eleventa
description: POS completo tipo Eleventa | Colombia
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BASE DATOS LOCAL
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # FORMATO MONEDA / FECHAS
  intl: ^0.19.0

  # ✅ LECTOR CÓDIGO BARRAS CÁMARA (versión estable)
  mobile_scanner: ^5.1.1

  # ✅ IMPRESORA TÉRMICA BLUETOOTH - VERSIÓN QUE SÍ FUNCIONA
  esc_pos_bluetooth: ^0.4.1
  flutter_bluetooth_serial: ^0.4.0

  # ✅ PDF BAJADO A 3.8.4 → SOLUCIONA EL CONFLICTO DE IMAGE
  pdf: ^3.8.4

  # EXCEL
  excel: ^3.0.0

  # NUBE FIREBASE
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5

  # PREFERENCIAS / SESIÓN
  shared_preferences: ^2.2.3

  # CIFRADO DIAN
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
